name: compile-and-upload-spa
on:
  push:
    branches: 
      - main
    paths:
      - "src/**"
  workflow_dispatch:

env:
  TENANT_ID: '655845bb-6fb9-4adf-bf80-5776ea887bc5'
  CLIENT_ID: '689078c3-c0ad-4c10-a0d3-1c430c2e471d'
  AUTHORITY: 'belleenetexternal.ciamlogin.com'
  POST_LOGOUT_REDIRECT_URI: 'photos.bellee.net'
  TOKEN_SCOPE: 'photo.all'
  TOKEN_ROLE: 'photo.upload'
  APP_NAME: 'photo-app'
  STORAGE_ACCOUNT_SUFFIX: 'blob.core.windows.net'

permissions:
  id-token: write
  contents: read
jobs:
  compile-and-upload-spa:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: create-tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
          
  deploy-to-staging:
    uses: cbellee/photo-spa/.github/workflows/deploy-workflow.yml@main
    secrets: inherit
    needs: [ compile-and-upload-spa ]
    concurrency: 
      group: staging-deploy
      cancel-in-progress: true
    if: github.ref == 'refs/heads/main' 
    with:
      environment: staging
      location: australiaeast
      app-name: ${{ vars.APP_NAME }}
      tenant-id: ${{ vars.TENANT_ID }}
      client-id: ${{ vars.CLIENT_ID }}
      authority: ${{ vars.AUTHORITY }}
      cname: photo-dev
      domain-name: ${{ vars.DOMAIN_NAME }}
      token-scope: ${{ vars.TOKEN_SCOPE }}    
      token-role: ${{ vars.TOKEN_ROLE }}
      storage-account-suffix: ${{ vars.STORAGE_ACCOUNT_SUFFIX }}
      post-logout-redirect-uri: ${{ vars.POST_LOGOUT_REDIRECT_URI }}

  deploy-to-production:
    uses: cbellee/photo-spa/.github/workflows/deploy-workflow.yml@main
    secrets: inherit
    needs: [ deploy-to-staging, compile-and-upload-spa ]
    concurrency: 
      group: production-deploy
      cancel-in-progress: true
    if: github.ref == 'refs/heads/main'
    with:
      environment: production
      location: uksouth
      app-name: ${{ vars.APP_NAME }}
      tenant-id: ${{ vars.TENANT_ID }}
      client-id: ${{ vars.CLIENT_ID }}
      authority: ${{ vars.AUTHORITY }}
      cname: photo
      domain-name: ${{ vars.DOMAIN_NAME }}
      token-scope: ${{ vars.TOKEN_SCOPE }}    
      token-role: ${{ vars.TOKEN_ROLE }}
      storage-account-suffix: ${{ vars.STORAGE_ACCOUNT_SUFFIX }}
      post-logout-redirect-uri: ${{ vars.POST_LOGOUT_REDIRECT_URI }}
    