name: compile-and-upload-spa
on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

#env:
  #TENANT_ID: '655845bb-6fb9-4adf-bf80-5776ea887bc5'
  #CLIENT_ID: '689078c3-c0ad-4c10-a0d3-1c430c2e471d'
  #AUTHORITY: 'belleenetexternal.ciamlogin.com'
  #POST_LOGOUT_REDIRECT_URI: 'photos.bellee.net'
  #TOKEN_SCOPE: 'photo.all'
  #TOKEN_ROLE: 'photo.upload'
  #LOCATION: 'uksouth'
  #APP_NAME: 'photo-app'
  #STORAGE_ACCOUNT_SUFFIX: 'blob.core.windows.net'

jobs:
  compile-and-upload-spa:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: gen-rg-name
        id: gen-rg-name
        run: |
            echo "rgName: ${{ vars.APP_NAME }}-${{ vars.LOCATION }}-rg"
            echo "rgName=${{ vars.APP_NAME }}-${{ vars.LOCATION }}-rg" >> "$GITHUB_ENV"

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deployment-outputs
        id: deployment-outputs
        uses: azure/CLI@v2
        with:
          azcliversion: 2.67.0
          inlineScript: |
            # get deployment output
            echo "STORAGE_ACCOUNT_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.storageAccountName.value -o tsv)" >> "$GITHUB_ENV"
            echo "PHOTO_API_ENDPOINT_URI=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.photoApiEndpoint.value -o tsv)" >> "$GITHUB_ENV"
            # echo "CDN_ENDPOINT_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.cdnEndpointName.value -o tsv)" >> "$GITHUB_ENV"
            # echo "CDN_PROFILE_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.cdnProfileName.value -o tsv)" >> "$GITHUB_ENV"

            echo "STORAGE_ACCOUNT_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.storageAccountName.value -o tsv)" 
            echo "PHOTO_API_ENDPOINT_URI=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.photoApiEndpoint.value -o tsv)"
            # echo "CDN_ENDPOINT_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.cdnEndpointName.value -o tsv)"
            # echo "CDN_PROFILE_NAME=$(az deployment group show --name deploy-infra --resource-group $rgName --query properties.outputs.cdnProfileName.value -o tsv)"
      
      - name: compile-spa
        id: compile-spa
        uses: azure/CLI@v2
        env:
          PHOTO_API_ENDPOINT_URI: ${{ env.PHOTO_API_ENDPOINT_URI }}
          STORAGE_ACCOUNT_NAME: ${{ env.STORAGE_ACCOUNT_NAME }}
        with:
          azcliversion: 2.67.0
          inlineScript: |
            echo "replacing tokens in apiConfig_template.ts..."
            sed "s|{{AZURE_TENANT_ID}}|${{ vars.TENANT_ID }}|g ; \
                s|{{STORAGE_ACCOUNT_NAME}}|${{ env.STORAGE_ACCOUNT_NAME }}|g ; \
                s|{{STORAGE_ACCOUNT_SUFFIX}}|${{ vars.STORAGE_ACCOUNT_SUFFIX }}|g ; \
                s|{{PHOTO_API_ENDPOINT_URI}}|${{ env.PHOTO_API_ENDPOINT_URI }}|g" \
                ./src/config/apiConfig_template.ts > ./src/config/apiConfig.ts

            echo "replacing tokens in msalConfig_template.ts"
            sed "s|{{CLIENT_ID}}|${{ vars.CLIENT_ID }}|g ; \
                s|{{AUTHORITY}}|${{ vars.AUTHORITY }}|g ; \
                s|{{REDIRECT_URI}}|${{ vars.CNAME }}-${{ vars.LOCATION }}.${{ vars.DOMAIN_NAME }}|g ; \
                s|{{TOKEN_SCOPE}}|${{ vars.TOKEN_SCOPE }}|g ; \
                s|{{TOKEN_ROLE}}|${{ vars.TOKEN_ROLE }}|g" \
                ./src/config/msalConfig_template.ts > ./src/config/msalConfig.ts

            echo "modified files..."
            cat ./src/config/apiConfig.ts
            cat ./src/config/msalConfig.ts
      
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: 18
      - run: | 
            npm install
            npm run build

      - name: upload-spa
        id: upload-spa
        uses: azure/CLI@v2
        env:
          STORAGE_ACCOUNT_NAME: ${{ env.STORAGE_ACCOUNT_NAME}}
          CDN_ENDPOINT_NAME: ${{ env.CDN_ENDPOINT_NAME }}
          CDN_PROFILE_NAME: ${{ env.CDN_PROFILE_NAME }}
        with:
          azcliversion: 2.67.0
          inlineScript: |
            # upload to Azure Blob Storage
            echo "Uploading SPA to Azure Blob Storage..."
            az storage azcopy blob upload --container '$web' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --source './dist/*' --recursive

            # purge the CDN cache 
            # echo "Purging the CDN cache..."
            # az cdn endpoint purge --resource-group $rgName --name ${{ env.CDN_ENDPOINT_NAME }} --profile-name ${{ env.CDN_PROFILE_NAME }} --content-paths "/*"